//commonjs, every file is module (by default)
//modules-encapsulated code (only share minmum)
const names = require ('./names')
const sayHi = require ('./utilss')
const data = require('./alternative-flavor')
require('./mind-grenade')
//sayHi('susan')
//sayHi(names.john)
//sayHi(names.peter)